# Generated by Django 4.1.5 on 2023-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0016_userdetailsmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
